apiVersion: apps/v1
kind: Deployment
metadata:
  name:  demoapp
  namespace: default
  labels:
    app:  demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  demoapp
    spec:
      containers:
      - name:  demoapp
        image:  busybox:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        args: ["sleep", "infinity"]
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always